name: 'barclays_workflow_poc'
version: '1.0.0'

profile: 'barclays_workflow_poc'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"
